server:
  port: 28086
spring:
  application:
    name: rocketmq-delay-consume-example
  cloud:
    stream:
      function:
        definition: consumer;producer;process
      rocketmq:
        binder:
          name-server: 192.168.134.89:9876 # 访问地址
        bindings:
          producer-out-0:
            producer:
              group: output_1
          producer-in-0:
            consumer:
              group: output_1
      bindings:
        producer-out-0:
          destination: delay
        consumer-in-0:
          destination: delay
          group: delay-group
        process-in-0:
          destination: delay
          group: delay-group1

logging:
  level:
    org.springframework.context.support: debug